import { auth } from '@/auth';
import OrbitingCirclesDemo from '@/components/Hero';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

export default async function Home() {
  /*
   * This happens when the session was generated by an old auth secret
   */
  const session = await auth();
  const cookieStore = cookies();
  const csrfToken = cookieStore.get('authjs.csrf-token');
  const sessionToken = cookieStore.get('authjs.session-token');

  if (session === null && (csrfToken || sessionToken)) {
    redirect('/force-signout');
  }
  return (
    <main className='flex h-screen flex-col items-center justify-center bg-gradient-to-b from-gray-600 to-gray-400 dark:from-[#2e026d] dark:to-[#15162c]'>
      <OrbitingCirclesDemo />
    </main>
  );
}
